enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
app-name = "YouTube"
rv-brand = "Morphe"
build-mode = "both"
version = "21.15.282"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
module-prop-name = "yt"
patcher-args = " -d 'Custom branding icon for YouTube' -d 'Custom branding name for YouTube' -e 'GmsCore support' -d 'Hide shortcuts' -d 'Enable debug logging' -e 'Settings for YouTube' -OrvxSettingsLabel='Customisation' -e 'Package name of YouTube' -OpackageNameYouTube='com.android.youtube' "

[Music]
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
app-name = "YouTube Music"
rv-brand = "Morphe"
build-mode = "both"
version = "9.15.50"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
module-prop-name = "ytm"
patcher-args = " -d 'Custom branding icon for YouTube Music' -d 'Custom branding name for YouTube Music' -e 'Settings for YouTube Music' -OrvxSettingsLabel='Customisation' -e 'Package name of YouTube Music' -OpackageNameYouTubeMusic='com.rvx.android.apps.youtube.music' "

[Reddit]
app-name = "Reddit"
rv-brand = "Morphe"
build-mode = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi"

[GooglePhotos]
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Twitch]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
