enable-magisk-update = true  # set false to disable module updates in Magisk app
patches-source = "anddea/revanced-patches"
rv-brand = "ReVanced eXtended"
parallel-jobs = 1

# To skip patching an app, either remove its section or add: enabled = false
# Detailed explanations: https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md

# ──────────────────────────────
# YouTube
# ──────────────────────────────
[YouTube]
build-mode = "both"
version = "20.21.37"
exclusive-patches = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "yt-rvx"
excluded-patches = ""
included-patches = ""
patcher-args = " -d 'Custom branding icon for YouTube' -d 'Custom branding name for YouTube' -e 'GmsCore support' -d 'Hide shortcuts' -d 'Enable debug logging' -e 'Settings for YouTube' -OrvxSettingsLabel='Customisation' -e 'Package name of YouTube' -OpackageNameYouTube='com.rvx.android.youtube' "

# ──────────────────────────────
# YouTube Music
# ──────────────────────────────
[Music]
arch = "both"
build-mode = "both"
version = "8.30.54"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytm-rvx"
app-name = "YouTube-Music"
excluded-patches = ""
included-patches = ""
patcher-args = " -d 'Custom branding icon for YouTube Music' -d 'Custom branding name for YouTube Music' -e 'Settings for YouTube Music' -OrvxSettingsLabel='Customisation' -e 'Package name of YouTube Music' -OpackageNameYouTubeMusic='com.rvx.android.apps.youtube.music' "
